### ISSUE TITLE
(tExtRef) Input restriction for ExtRefs

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-lib#8]
Similar to #7 we should be able to show the restriction for an ExtRef in terms of the basic type and cdc:

Currently we do:

```ts
/**
 * Edition 2 and later SCL files allow to restrict subscription on
 * later binding type inputs (`ExtRef` elements) based on a `CDC` and
 * basic type `bType`.
 * @param extRef - A later binding type input in the sink IED
 * @returns data objects `CDC` and data attribute basic type `bType` or `null`
 */
export function inputRestriction(extRef: Element): {
  cdc: string | null;
  bType: string | null;
} {
  const [pLN, pDO, pDA] = ['pLN', 'pDO', 'pDA'].map(attr =>
    extRef.getAttribute(attr)
  );
  if (!pLN || !pDO || !pDA) return { cdc: null, bType: null };

  const anyLns = Array.from(
    extRef.ownerDocument.querySelectorAll(
      `LN[lnClass="${pLN}"],LN0[lnClass="${pLN}"]`
    ) ?? []
  );

  for (const anyLn of anyLns) {
    const dataSpec = dataAttributeSpecification(anyLn, pDO, pDA);
    if (dataSpec.cdc !== null && dataSpec.bType !== null) return dataSpec;
  }

  return { cdc: null, bType: null };
}

```

I'd like to export this so I can show this in a hover for ExtRefs in the later binding plugin.

There is a little question in my mind around the way pDO is used.

Currently we use the pDO to derive the CDC but Ed 2.1 appears to also allow the option of a DO _name_.  Either this should be a parameter or it is just a mistake in the standard:

![image](https://github.com/OpenEnergyTools/scl-lib/assets/674783/38f70dda-1bdc-46bb-b098-1d507dd6f5d6)

Most of part 6 and part 7-1 suggest that the pDO should only be used for the CDC but there is this inconsistency

**Comment by JakobVogelsang** [comment]
I think this is both, if you ask me. This is currently in development and is part of the `subscribe` function and what makes it a bit more tricky to implement compared to the `unsubscribe` function. 

I think we need to check for both the `doName` and the `CDC` it is pointing to. The problem is how to get the `CDC`. I think for the `pDO` it must go through the name space description rather than the data model of the subscriber IED (this is what we do now). I do think that because of some indicators (although I must say this is all both clearly defined in the standard):
1. `pDO` can be the only attribute. It might happen that there is no `pLN` and then navigating through the date model is not really possible.
2. The sentence from the 9.3.13 of the 2007B4 saying `The pDO might specify via a standardized DO name the needed input CDC`. 

I did therefore transform the NSD files 7-4 and 7-3 to something like this:

```json
{
  "A": {
      cdc: WYE,
      children: {...}
   }
   "A.phsA": {
       cdc: CMV,
       children: {... cVal.mag.f: 'FLOAT32'}
    }
}
```

The parsing for the `CDC` and `bType` is then very easy and there is no need anymore to parse through the data model as we need to do for the FCDA to get `CDC` and `bType`.

**Comment by danyill** [comment]
That's really interesting, thanks.

**Comment by danyill** [comment]
Currently in subscriber later binding, there is quite a severe performance limitation incurred by trying to look these up, so I am quite pleased you have considered an alternative approach :+1:
